### ISSUE TITLE
Empty scaffold list files

### ISSUE THREAD

**Issue by ghost** [kbseah/genome-bin-tools#34]
Normally I run this code with no issues at all. I use GBTools to interactively/manually delineate my bins. However, for some reason it is saving an empty (1 byte) list file; i.e., my bin.connected.scaffolds.list file is created but is only 1 byte and does not actually contain a list. I'm not sure what is wrong or what to do. My imported files (assembly_graph.fastg, scaffolds.paths and scaffolds.fasta files are 84.5MB, 7.2MB, and 39.1MB respectively, and the differential coverage and GC plots are created successfully, so I don't think it's a problem with the  files the code is calling on.

I tried updating my R (to 4.0.0) to see if this would resolve the issue, but that created a whole bunch of new problems (I believe with incompatibilities with package versions, but I am new to R so not sure. All I know is it was very irksome to troubleshoot, so I went back to version 3.5.2)

**For the part of the code that gives me issues**
'
<img width="1222" alt="Screen Shot 2020-05-26 at 3 07 47 PM" src="https://user-images.githubusercontent.com/47035328/82945761-ea048e80-9f62-11ea-920a-c230148da605.png">
`> bin <- choosebin(d,slice=1,save=TRUE,file="bin.scaffolds.list",num.points=15)
Loading required package: sp
> bin.connected <- fastgFish(d,bin,fastg.file="assembly_graph.fastg",paths.file="scaffolds.paths",fasta.file="scaffolds.fasta",script.path="/Users/mhauer32/Documents/Beinart_Lab/Marianas_Project/Genome_assembly_final/Spades2_5k/fastg_paths_fishing.pl",depth=1,save=TRUE,file="bin.connected.scaffolds.list")
Warning messages:
1: In system2(command, command.params, input = as.character(bin$scaff$ID),  :
  running command ''perl' /Users/mhauer32/Documents/Beinart_Lab/Marianas_Project/Genome_assembly_final/Spades2_5k/fastg_paths_fishing.pl -g assembly_graph.fastg -p scaffolds.paths -s scaffolds.fasta -o /tmp/tmp.fishing_output -b - -i 1 -r 2>/dev/null < '/var/folders/qx/zjx9f11d0tjc0qdf8x5c08r40000gn/T//RtmpXB6VHZ/file12caf2980a940'' had status 2
2: In max(scaff.subset$Length) :
  no non-missing arguments to max; returning -Inf
3: In min(scaff.subset$Length) :
  no non-missing arguments to min; returning Inf`

**for the entire code**
'<img width="1237" alt="Screen Shot 2020-05-26 at 3 07 40 PM" src="https://user-images.githubusercontent.com/47035328/82945811-03a5d600-9f63-11ea-9a53-0c04259e1dae.png">
`> d <- gbt(covstats=c("Mar13_symbiont3_5k.coverage.mod", "Mar11_symbiont3_5k.coverage.mod"),mark="phylotype.result.parsed.mod",marksource="amphora2",ssu="Mar13_symbiont3_5k.ssu.tab.mod")
> col <- data.frame(c("Gammaproteobacteria"),c("red"))
> plot(d,slice=c(1,2),ssu=TRUE,trna=TRUE,markCustomPalette=col,taxonLevel="Class",legend=TRUE)
> plot(d,ssu=TRUE,trna=TRUE,markCustomPalette=col,taxonLevel="Class",legend=TRUE)
> pdf("DiffCov.pdf")
> plot(d,slice=c(1,2),ssu=TRUE,trna=TRUE,markCustomPalette=col,taxonLevel="Class",markCutoff=1.0,legend=TRUE)
> dev.off()
quartz 
     2 
> pdf("GCCov.pdf")
> plot(d,ssu=TRUE,trna=TRUE,markCustomPalette=col,taxonLevel="Class",markCutoff=1.0,legend=TRUE)
> dev.off()
quartz 
     2 
> bin <- choosebin(d,slice=1,save=TRUE,file="bin.scaffolds.list",num.points=15)
Loading required package: sp
> bin.connected <- fastgFish(d,bin,fastg.file="assembly_graph.fastg",paths.file="scaffolds.paths",fasta.file="scaffolds.fasta",script.path="/Users/mhauer32/Documents/Beinart_Lab/Marianas_Project/Genome_assembly_final/Spades2_5k/fastg_paths_fishing.pl",depth=1,save=TRUE,file="bin.connected.scaffolds.list")
Warning messages:
1: In system2(command, command.params, input = as.character(bin$scaff$ID),  :
  running command ''perl' /Users/mhauer32/Documents/Beinart_Lab/Marianas_Project/Genome_assembly_final/Spades2_5k/fastg_paths_fishing.pl -g assembly_graph.fastg -p scaffolds.paths -s scaffolds.fasta -o /tmp/tmp.fishing_output -b - -i 1 -r 2>/dev/null < '/var/folders/qx/zjx9f11d0tjc0qdf8x5c08r40000gn/T//RtmpXB6VHZ/file12caf2980a940'' had status 2
2: In max(scaff.subset$Length) :
  no non-missing arguments to max; returning -Inf
3: In min(scaff.subset$Length) :
  no non-missing arguments to min; returning Inf
`

**the programs I installed to run this code (package, version, built):**

sp : 1.4-1 3.5.2

plyr : 1.8.6 3.5.2

devtools : 2.3.0 3.5.2

rlang : 0.4.3 3.5.2

gbtools : 2.6.0 3.5.2

**Comment by kbseah** [comment]
Hello @minna-miha, thanks for getting in touch. 

When you ran the `fastgFish` command, you specified a path to the `fastg_paths_fishing.pl` script: 
```
bin.connected <- fastgFish(d,bin,fastg.file="assembly_graph.fastg",paths.file="scaffolds.paths",fasta.file="scaffolds.fasta",script.path="/Users/mhauer32/Documents/Beinart_Lab/Marianas_Project/Genome_assembly_final/Spades2_5k/fastg_paths_fishing.pl",depth=1,save=TRUE,file="bin.connected.scaffolds.list")
```

To clarify, why did you specify the path with the `script.path` parameter, instead of leaving it as default? Were there any problems with the default script that should be in the R package folder?

The command `fastgFish` is just a wrapper for the Perl script. I see that you have saved the contig list for your bin to the file `bin.scaffolds.list`. Could you please run the Perl script on its own, with the following command, and report the error messages that pop up? 

```
perl fastg_paths_fishing.pl -b bin.scaffolds.list -p scaffolds.paths -g assembly_graph.fastg -s scaffolds.fasta -i 1 -o bin_connected_test
```

To find the path to the `fastg_paths_fishing.pl` script that is bundled with the R package, use the following command within the R environment:

```
system.file("Perl","fastg_paths_fishing.pl",package="gbtools")
```

**Comment by ghost** [comment]
Hi @kbseah, thank you for your help!

1. Re: use of 'script.path', I'm not sure: this is a hand-me-down script from someone else (though this script has previously given me no problems)

2. The error that comes up is `Error: unexpected symbol in "perl fastg_paths_fishing.pl"`

3. Are you suggesting in the last command, the path should be edited to match the result of the `system.file("Perl","fastg_paths_fishing.pl",package="gbtools")` ? I did this and the file seems to be populated now! Thank you!

**Comment by kbseah** [comment]
Hello @minna-miha ,

Thanks for the clarification. Given that the script was a hand-me-down, I think what happened was the following: 
The script was originally running fine because user Mhauer32 kept a separate copy of the `fastg_paths_fishing.pl` file located at: /Users/mhauer32/Documents/Beinart_Lab/Marianas_Project/Genome_assembly_final/Spades2_5k/fastg_paths_fishing.pl 
However this was subsequently moved or deleted, so the script stopped working. 

You state that the `fastgFish` command runs fine when you update the `script.path` parameter to match the output of `system.file("Perl","fastg_paths_fishing.pl",package="gbtools")`. That's good, because that's how it should work. You don't normally need to specify `script.path` explicitly, because by default it knows where to look, so in the future you can leave that parameter out.

By the way the gbtools suite is quite old, I'm flattered that you're still using it, but perhaps also consider looking at other software for metagenome binning. The [CAMI challenge paper](https://www.nature.com/articles/nmeth.4458) describes the state of the art around 2017. For visualization and interactive binning some colleagues like [anvio](http://merenlab.org/software/anvio/). Wishing you all the best for your research!

**Comment by kbseah** [comment]
Closing as the issue appears to be resolved. Please open new issue if further help needed.
